title: Site

tabs:
  main:
    label: Main
    icon: text
    columns:
      main_1:
        width: 1/2
        sections:
          # The `pages` pages section shows other main pages of the site
          # Using the `templates` option, we limit which types of pages are shown
          # Using the `create` option, we limit the type of page that can be created when a new page is created
          # Note that the `sandbox` page and the `error` page that also exist in the content folder but use different blueprints thus do not show up in the list
          # Since the error page's blueprint is set to `read: false`, it wouldn't show up here even if you added the error blueprint to the templates list
          recipes:
            parent: site.find("recipes")
            headline: Recipes
            type: pages
            sortBy: title
            limit: 30
            info: "{{page.author}}"
            templates:
              - recipe
      main_2:
        width: 1/2
        sections:
          pages:
            headline: Pages
            type: pages
            sortable: true
            templates:
              - default
              - home
          error_page:
            headline: Error
            type: pages
            templates:
              - error
          info:
            type: info
            headline: Formatting
            text: |
              For more information on formatting, visit [this Kirby guide](https://getkirby.com/docs/guide/content/text-formatting)
              or [this Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet).
  settings:
    label: Settings
    icon: cog
    columns:
      settings_1:
        width: 1/2
        fields:
          ga:
            label: Google Analytics Code
            type: text
          meta_description:
            label: Site Meta Description
            type: text
      # settings_2:
      #   width: 1/2
      #   fields:
      #     footer
      #       label: Footer
      #       type: textarea
